### ISSUE TITLE
npm start not working in menu component

### ISSUE THREAD

**Issue by isadaqah** [react-component/rc-server#1]
```
../menu/node_modules/rc-server/index.js:117
  app.get('/tests/runner.html', function *() {
                                         ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/adminuser/projects/menu/node_modules/rc-server/bin/start.js:1:73)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by yiminghe** [comment]
install node 0.12

**Comment by isadaqah** [comment]
Thanks
